apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: namespace-as-a-service
spec:
  schema:
    apiVersion: v1alpha1
    kind: NamespaceAsAService
    spec:
      name: string
      labels: string | default=""
    status:
      namespaceName: string
  resources:
    - id: ns
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.name}
